title: JSON Schema Everywhere
description: Tracking schema validation and editor support of data description languages.
github_username: json-schema-everywhere
google_analytics: UA-101483402-1
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE.txt
  - _languages/json.md
collections:
  languages:
    output: true
    permalink: '/:path'

defaults:
  - scope:
      path: ''
      type: languages
    values:
      layout: language